version: '3'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
  jekabot:
    container_name: jekabot
    build: .
    depends_on:
      - wireguard
    network_mode: "service:wireguard"
    volumes:
      - .:/app
